### ISSUE TITLE
Ensure analytics are set up

### ISSUE THREAD

**Issue by naps62** [subvisual/blog#18]

**Comment by naps62** [comment]
@fribmendes can you point me to which lines (on the current blog) are necessary? I only know of the GA script tag

**Comment by frm** [comment]
I don't think the current blog has Google Search Console enabled, but we do have to set it up. Other than SC, we only need GA.

**Comment by frm** [comment]
On the main website, Search Console is set up. Check these [two](https://github.com/subvisual/subvisual.co/commit/37ba17f334471598daad68b953be97ef321261f9) [commits](https://github.com/subvisual/subvisual.co/commit/efedfe25f0eabeee5f035aef47b5c3941027de0a)
